### ISSUE TITLE
Bug: Player cannot go through Portals (May be duplicate of tunnel bug)

### ISSUE THREAD

**Issue by sos0** [norestlabs/BrowserQuest#18]
Tested on Firefox
Walked into a portal and the game froze. (Same with houses)
Single player was on the screen at the time.

Cannot reproduce this bug when there is only 1 player online in the game.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1973082/51151158-8458ac00-181e-11e9-9c3d-aa6f7bb93e37.png">

**Comment by sos0** [comment]
This might be the same bug as the tunnel bug.

**Comment by oleg-baturov** [comment]
Verified by e179a42
