### ISSUE TITLE
Bug: Freeze while moving

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/BrowserQuest#24]
- Frequency: once

-  Condition
```
2 players
player1 is fighting
player2 moves to the screen
```

- freeze screen
![image](https://user-images.githubusercontent.com/32242962/51341275-b0a15080-1adc-11e9-9f7c-83de04ba226c.png)

- console log
![image](https://user-images.githubusercontent.com/32242962/51341348-dd556800-1adc-11e9-905f-a74d28ba1b7b.png)

- code
```
if (loot.enabled && loot.target && loot.target.getComponent(_Components.Transform).GridPosition.equals(player.getComponent(_Components.Transform).GridPosition)) {
```
![image](https://user-images.githubusercontent.com/32242962/51341429-00801780-1add-11e9-8fb0-c3eb50289eb5.png)

**Comment by gedanziger** [comment]
![image](https://user-images.githubusercontent.com/5342263/51347582-5c9f5900-1a55-11e9-8357-68a18cc8e331.png)
Reproduced @oleg-baturov 's bug @alexey-shved
