### ISSUE TITLE
Need to change title across game from "BrowserQuest" to "BlockchainQuest"

### ISSUE THREAD

**Issue by Eskew** [norestlabs/BrowserQuest#29]
Canaan Linder has requested the name change from "BrowserQuest" to "BlockchainQuest" per Stardust's instructions.

This includes the existing domain, in-game references, and title screen headlines along with any references while playing.

**Comment by sos0** [comment]
Progress for this lives in branch `blockchain-quest`

**Comment by Eskew** [comment]
New title screen will be created by Bryan May and uploaded here for use in-game once completed

**Comment by Eskew** [comment]
![bws](https://user-images.githubusercontent.com/45974902/52005054-90c74080-247d-11e9-9a42-be0ec1bf24d0.png)
<img width="687" alt="screen shot 2019-01-28 at 2 51 33 pm 1" src="https://user-images.githubusercontent.com/45974902/52005055-90c74080-247d-11e9-9b60-ffbbeefb2708.png">
<img width="687" alt="screen shot 2019-01-28 at 2 51 33 pm" src="https://user-images.githubusercontent.com/45974902/52005057-915fd700-247d-11e9-9c0c-9453bada97ce.png">

**Comment by Eskew** [comment]
![blockchainquest](https://user-images.githubusercontent.com/45974902/52005091-ad637880-247d-11e9-8a26-2191738c7964.png)

Single line format
