### ISSUE TITLE
Create new on-screen scroll popup for each item generated in-game

### ISSUE THREAD

**Issue by Eskew** [norestlabs/BrowserQuest#30]
<img width="810" alt="screen shot 2019-01-17 at 7 04 49 pm" src="https://user-images.githubusercontent.com/45974902/51636522-5d7d3280-1f0e-11e9-833f-6844f54151ab.png">

Each item will need to be imported into a generated scroll screen with the option to View on Blockchain and View on Marketplace along with an Equip to Character functionality.

**Comment by oleg-baturov** [comment]
@Eskew 
Plz clarify logic for each case of `View on Marketplace` and `View on Blockchain`.

**Comment by Eskew** [comment]
> @Eskew
> Plz clarify logic for each case of `View on Marketplace` and `View on Blockchain`.

@oleg-baturov we will have clarification for the process tomorrow AM once we speak with Canaan for the behaviors, will update as soon as I have the logic in place

**Comment by Eskew** [comment]
Updated Login logic
1.) Login to Stardust account (currently in mock format)
2.) Login to BlockchainQuest game- want to change this to some sort of store on backend, local storage, which associates name and IP with a wallet; want to generate wallets when they login
3.) Create wallet function from Stardust API, returning private/public keys, eventually migrate to Temp function- only get public address and just have access to sign transactions with game address so no one stores users private key
4.) Link Temp functionality to Marketplace

**Comment by Eskew** [comment]
in game, when clicking "View on Marketplace" they will be prompted to login to their Stardust marketplace account to continue

1. user clicks view in stardust marketplace on parchment popup
2. backend checks if user is already linked. If not, open a popup and go to stardust to click approve with their account
3. Once approved, view the item within the stardust marketplace

**Comment by gedanziger** [comment]
@oleg-baturov @sos0 @Eskew For starting, we should do it mock behavior according to #33 . The marketplace can pre-fill mock data to give a demonstration first

**Comment by oleg-baturov** [comment]
Verified by 0300c64
