### ISSUE TITLE
Mock Marketplace Logic

### ISSUE THREAD

**Issue by gedanziger** [norestlabs/BrowserQuest#33]
Create a mock link to the marketplace wallet of the user. Create a url in the format:

https://base-url/path/.../walletdemo?address=0xafee908ad9-0dsa90d9a90-890-890f&item=Red%20Armor&item=Blue%20Sword&item=Magic%20Sword

The final url should contain
- `address` - user's eth address
- `item` - array of items, one for each copy in inventory

The marketplace should be able to render a mock version of the wallet from the above, for demo purposes until the full wallet integration is built.

**Comment by Eskew** [comment]
View on Marketplace button should link to the following URL: https://stardust.exchange/demo-dash?inventory[]=BlueSword&inventory[]=RedSword 

This will be used for demo purposes but should take the User to the Stardust exchange screen showing the items in the mock account.
