### ISSUE TITLE
[Bug] Incomplete player sprite on loading screen

### ISSUE THREAD

**Issue by sos0** [norestlabs/BrowserQuest#37]
![image](https://user-images.githubusercontent.com/1973082/52093807-7ec6ca00-2571-11e9-8ddb-f0fdea3b3199.png)
![image](https://user-images.githubusercontent.com/1973082/52093813-825a5100-2571-11e9-9812-859849914f61.png)

**Comment by oleg-baturov** [comment]
Verified by 454cc06a64816b531a9b469a50ccc0ae955708c1
