### ISSUE TITLE
Hide User wallet on main BlochchainQuest login screen

### ISSUE THREAD

**Issue by Eskew** [norestlabs/BrowserQuest#39]
Instead of having the Wallet Address as a field below "Name Character" we should have it hidden and put a "View wallet address" button on the top right which will then display the user's wallet address for Blockchain quest.

This will make it more user-friendly for non-blockchain users and was requested by Canaan on 2/5. 

<img width="712" alt="screen shot 2019-02-06 at 11 10 29 am" src="https://user-images.githubusercontent.com/45974902/52366970-d5b02180-29ff-11e9-9d3b-25fe8f5f159c.png">

Wallet logo should be in white to match the information banner top right on existing login page

**Comment by Eskew** [comment]
This could either be a button or another red banner like the information one with a wallet image on it which would link to their generated Eth wallet address.

![wallet](https://user-images.githubusercontent.com/45974902/52303433-d3d55800-2944-11e9-8e6f-2d17b0e3e338.jpg)

**Comment by Eskew** [comment]
Toggle "On" for wallet view

<img width="788" alt="screen shot 2019-02-07 at 11 02 28 am" src="https://user-images.githubusercontent.com/45974902/52435949-e88e2900-2ac7-11e9-933e-8c1c7e889ec2.png">

Toggle "Off" for no wallet view

<img width="788" alt="screen shot 2019-02-07 at 11 02 28 am" src="https://user-images.githubusercontent.com/45974902/52435977-f774db80-2ac7-11e9-8aa1-d953da3f738c.png">

**Comment by sos0** [comment]
New spec:
Replace upper right red banner with wallet functionality as described in the original issue/comment.
