### ISSUE TITLE
[Bug] Player Health Recovery

### ISSUE THREAD

**Issue by sos0** [norestlabs/BrowserQuest#42]
### Bug Description
- When the player gets damaged, there is no more health recovery unless the player drinks a potion.
- This is a low priority bug as it only affects difficulty of the gameplay.

### Expected Behavior
- The player should always heal up to 100% over time.

**Comment by oleg-baturov** [comment]
Verified by 42a891a4f84fc5c9030dc6455f1248503f4a5bb4
