### ISSUE TITLE
Sound button in-game doesn't work when muted

### ISSUE THREAD

**Issue by Eskew** [norestlabs/BrowserQuest#45]
Unable to toggle the sound on/off in-game but selecting/deselecting the Sound button bottom right screen. 

In-game actions like attacking and movement are still heard when the sound button is disabled (muted).

<img width="1011" alt="screen shot 2019-02-14 at 5 06 13 pm" src="https://user-images.githubusercontent.com/45974902/52827749-eb19f100-307a-11e9-9440-f0fd9debae8a.png">

**Comment by oleg-baturov** [comment]
Verified by 42a891a4f84fc5c9030dc6455f1248503f4a5bb4
