### ISSUE TITLE
Implement Mintable Items

### ISSUE THREAD

**Issue by gedanziger** [norestlabs/BrowserQuest#5]
For each of the types of items defined inside the game, mint a copy for a user:

- Using the method in the stardust SDK ([LINK HERE](https://www.dropbox.com/s/jww6x2tfx9u1iuq/stardust.js?dl=0)) Add all items issued in game as types of items. Issue a copy to the player when it is picked up in game.

All of the items with these types (`Weapon`, `Armor`, `Object`) should be mintable:

```
        sword1: [Entities.Sword1, "weapon"],
        sword2: [Entities.Sword2, "weapon"],
        axe: [Entities.Axe, "weapon"],
        redsword: [Entities.RedSword, "weapon"],
        bluesword: [Entities.BlueSword, "weapon"],
        goldensword: [Entities.GoldenSword, "weapon"],
        morningstar: [Entities.MorningStar, "weapon"],
        
        firefox: [Entities.Firefox, "armor"],
        clotharmor: [Entities.ClothArmor, "armor"],
        leatherarmor: [Entities.LeatherArmor, "armor"],
        mailarmor: [Entities.MailArmor, "armor"],
        platearmor: [Entities.PlateArmor, "armor"],
        redarmor: [Entities.RedArmor, "armor"],
        goldenarmor: [Entities.GoldenArmor, "armor"],

        flask: [Entities.Flask, "object"],
        cake: [Entities.Cake, "object"],
        burger: [Entities.Burger, "object"],
        chest: [Entities.Chest, "object"],
        firepotion: [Entities.FirePotion, "object"],
```

![stardust items flow](https://user-images.githubusercontent.com/5342263/50610504-085a7d80-0e88-11e9-9f83-6bed9cb5255e.png)

**Comment by oleg-baturov** [comment]
@sunrisepopov 
Instead of `sand or live` domain, you need to use `http://68.183.20.43:3000/` for now.
It is testnet.
