### ISSUE TITLE
Add Database + Pending Transaction

### ISSUE THREAD

**Issue by gedanziger** [norestlabs/BrowserQuest#8]
Integrate MySQL + Sequelize to hold pending transactions. When a new item is added, call the mint call using the contract hash from #7 and the mint call from #5. Keep the transaction as pending until it appears in-game.

**Comment by oleg-baturov** [comment]
@gedanziger 
We should store tx_hashes in db, and monitor tx status by using cron?

All stardust apis return create result instantly and they say `api response` means `tx completion` on loom chain.
If it is, we don't have to use our db and we don't need cron service to monitor txs.

Your thought?

**Comment by gedanziger** [comment]
Closing this issue for now, as unneeded for mvp @oleg-baturov @sunrisepopov
